# Generated by Django 5.1.5 on 2025-02-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
